version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-aula02-fundamentos-app
    volumes:
      - .:/app
    networks:
      - react-aula02-fundamentos-network
    working_dir: /app  # Adicionado o diretório de trabalho

  nginx:
    image: nginx
    container_name: react-aula02-fundamentos-nginx
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "8080:80"
    networks:
      - react-aula02-fundamentos-network
    depends_on:
      - app

  postgres:
    image: postgres
    container_name: react-aula02-fundamentos-postgres
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - react-aula02-fundamentos-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: react-aula02-fundamentos-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@react-aula02-fundamentos.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - react-aula02-fundamentos-network

networks:
  react-aula02-fundamentos-network:
